In [1]:
import numpy as np

In [11]:
A1=np.array([[1,2,3],[4,5,6],[7,8,9]])
A2=np.random.random((3,3))

In [12]:
A2

array([[0.23915119, 0.5912824 , 0.5780674 ],
       [0.08959898, 0.99095259, 0.02097046],
       [0.06019645, 0.63528593, 0.27208259]])

In [5]:
A3=np.eye(7)

In [6]:
A3

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [9]:
A4=np.zeros((5,6))

In [10]:
A4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.transpose(A1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [14]:
np.linalg.det(A1)

-9.51619735392994e-16

In [15]:
np.linalg.matrix_rank(A1)

2

In [16]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
res2=np.array([[7,4],[5,3]])
res=np.linalg.inv(np.array([[7,4],[5,3]]))

In [24]:
res@res2

array([[ 1.00000000e+00,  0.00000000e+00],
       [-3.55271368e-15,  1.00000000e+00]])

In [22]:
res3=np.linalg.inv(A1)

In [23]:
A1@res3

array([[ 0. ,  1. , -0.5],
       [ 0. ,  2. , -1. ],
       [ 0. ,  3. ,  2.5]])

In [26]:
A5=np.array([[-1,-6],[2,6]])

In [27]:
np.linalg.eigvals(A5)

array([2., 3.])

In [29]:
res1=np.linalg.eig(A5)

In [30]:
res2=np.transpose(res1[1])

In [31]:
res2

array([[-0.89442719,  0.4472136 ],
       [ 0.83205029, -0.5547002 ]])

In [33]:
res2[0]/0.4472136

array([-1.99999998,  0.99999999])

In [34]:
res2[1]/-0.5547002

array([-1.49999999,  0.99999999])